### ISSUE TITLE
Update testing/install instructions for all controllers

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#133]
- [x] https://github.com/fluxcd/helm-controller/issues/341
- [x] https://github.com/fluxcd/source-controller/issues/454
- [x] https://github.com/fluxcd/notification-controller/issues/265
- [x] https://github.com/fluxcd/image-automation-controller/issues/237
- [x] https://github.com/fluxcd/kustomize-controller/issues/468
- [x] https://github.com/fluxcd/image-reflector-controller/issues/182

**Comment by stefanprodan** [comment]
All these issues should be called "Review/extend DEVELOPMENT documentation" as CONTRIBUTING.md has been deleted from all repos.

**Comment by yiannistri** [comment]
I would like to work on these issues @kingdonb 🙏

**Comment by kingdonb** [comment]
Great, thanks @yiannistri I assigned this one to you for tracking. Let me know if there's anything I can help! I spent some time yesterday to try and close out image-reflector-controller#182
