### ISSUE TITLE
📈 Use Contributor Ladder more

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#227]
In #203 and #207 we built a contributor ladder, where

- contributors from all over the place (no matter if they write code or not) can become project members - so far @staceypotter and @Arhell followed the process
- the rules for joining the ranks of @fluxcd/maintainers (for any given Flux project) or `@fluxcd/core-maintainers` are a lot clearer

We defined roles like those of `@fluxcd/org-admins` or the [Security Team](https://fluxcd.io/security/#security-team) as well.

This is all great, and provides a great groundwork. The process and infrastructure is in place. We now want more people to join as contributors, decision makers and maintainers and keep them involved. Additionally we want for the group to be more diverse. Flux having been started at Weaveworks still shows its signs - many key contributors still work at Weaveworks.

Let's treat this as a meta issue from which we start the discussion and individual initiatives to address this.

- [x] create "ladder :ladder:" issue label, so we track all the relevant issues easily: https://github.com/fluxcd/community/labels/ladder%20%F0%9F%AA%9C
- [ ] https://github.com/fluxcd/community/issues/228
- [ ] https://github.com/fluxcd/community/issues/229
- [ ] https://github.com/fluxcd/community/issues/230 
- [ ] https://github.com/fluxcd/community/issues/231

**Comment by dholbach** [comment]
It'd be good to address the various ways of being involved in the project (advocacy, docs, events, testing, writing code, etc) and the various stages of involvement (learning about flux and its community, finding a way to be involved, joining the community through e.g. meeting/slack as well, progressing on the contributor ladder, ...)

My proposal would be that we comment with ideas to address this and if there's folks who would like to be involved with either of them, choose a reaction of your liking to indicate you'd be happy to participate. We can then file a separate issue to start implementing it?

**Comment by dholbach** [comment]
An idea I would love to work on myself is: **a welcome committee**. Maybe we could use a fixed time in the Flux Dev meetings to take a look at who contributed PRs recently and make sure we invite them to Dev meeting, our Slack and generally make sure they have everything they need.

A small script like

```cli
for repo in $(gh api -H "Accept: application/vnd.github+json" /orgs/fluxcd/repos | jq '.[].full_name' | cut -d'"' -f2); do \
    gh pr list -s merged -L 1000 -S 'closed:>2022-08-01' \
        -R $repo --json url,title,author
        --template   '{{range .}}{{tablerow .author.login .url .title}}{{end}}'; \
done | sort
```

Could be helpful for that. The script above is just a little bit of toying around on my part - and just to illustrate what we could do.

**Comment by dholbach** [comment]
Another idea could be to reevaluate our participation in GSoC and similar events.

**Comment by dholbach** [comment]
What also came up in a discussion was to e.g. steal one of the Bug Scrub sessions a month and turn it into a "How to start with Flux development" session.

**Comment by makkes** [comment]
One low-hanging fruit is to call out first-time contributors more as soon as a new release goes out.

**Comment by dholbach** [comment]
> One low-hanging fruit is to call out first-time contributors more as soon as a new release goes out.

@makkes You mean giving them a mention in the release announcement?

**Comment by hiddeco** [comment]
> You mean giving them a mention in the release announcement?

I am very much in favor of this, as it used to work great for Flux version 1. But it would require a bit more thinking in terms of automation given the increased complexity of our release processes.

**Comment by pjbgf** [comment]
Based on a chat with @makkes, I created a board view for new contributors to find items that are waiting for contributors.
We could share this profusely and see whether it lowers the entry bar to first contributions.

To add issues into that specific board view, they need to be labelled `help wanted` and added into the [Maintainers' Focus](https://github.com/orgs/fluxcd/projects/6/views/16) project.
