### ISSUE TITLE
Reschedule meetings using CNCF Zoom

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#26]
Google Meet stopped allowing to record, so let's move to CNCF Zoom infrastructure for our meetings. Date and times will stay the same.

@squaremo offered help testing and double-checking calendar settings.

### To-do

- [x] Schedule meetings
- [x] Figure out https://lists.cncf.io/g/cncf-flux-dev/calendar vs https://www.cncf.io/calendar/ situation
- [x] Announce on Slack(s)
- [x] Announce on mailing list
- [x] Update https://github.com/fluxcd/community instructions
- [x] Update https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/edit

**Comment by dholbach** [comment]
So I tried this and get stuck at the point where I try to "make this a zoom meeting". I follow the Zoom SSO flow and get stuck at

> This app requires pre-approval by your account admin. You may reload this page and click on "Request pre-approve".

**Comment by dholbach** [comment]
- [ ] Schedule meetings
- [ ] Figure out https://lists.cncf.io/g/cncf-flux-dev/calendar vs https://www.cncf.io/calendar/ situation
- [ ] Announce on Slack(s)
- [ ] Announce on mailing list
- [ ] Update https://github.com/fluxcd/community instructions
- [ ] Update https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/edit

**Comment by scottrigby** [comment]
- We have moved Flux events to the CNCF calendar https://www.cncf.io/calendar/ - We just need to announce to Flux users to subscribe to that calendar instead. Then we could give a period of time before removing our events from the list calendar (so they don't get out of sync)?
- We probably want to set up a shard Zoom account. I believe CNCF helps with this - can request in Service Desk

**Comment by dholbach** [comment]
It'd be good if we could tie this all up before the Thursday meeting.

**Comment by dholbach** [comment]
Once the cncf.io/calendar situation is resolved, this issue can be closed.
